Repository KOSA-4Back/RunUs_BE, pull requests merged in 2024-07, with the labels that each got.

#3 Feat TopicExchange
  .idea/dataSources.xml
  .idea/material_theme_project_new.xml
  src/main/java/com/fourback/runus/domains/member/controller/MemberController.java
  src/main/java/com/fourback/runus/domains/member/domain/Member.java
  src/main/java/com/fourback/runus/domains/member/dto/message/ReceiveMemberUpdateFormatter.java
  src/main/java/com/fourback/runus/domains/member/dto/requeset/SendCreateMemberRequest.java
  src/main/java/com/fourback/runus/domains/member/dto/requeset/SendDeleteMemberRequest.java
  src/main/java/com/fourback/runus/domains/member/dto/response/FindMembersResponse.java
  src/main/java/com/fourback/runus/domains/member/repository/MemberRepository.java
  src/main/java/com/fourback/runus/global/error/errorCode/ResponseCode.java
  src/main/java/com/fourback/runus/global/rabbitMQ/config/MQConfig.java
  src/main/java/com/fourback/runus/global/rabbitMQ/config/MainServerConfig.java
  src/main/java/com/fourback/runus/global/rabbitMQ/enumerate/MQExchange.java
  src/main/java/com/fourback/runus/global/rabbitMQ/exchange/DirectExchangeConfig.java
  src/main/java/com/fourback/runus/global/rabbitMQ/exchange/TopicExchangeConfig.java
  src/main/java/com/fourback/runus/global/rabbitMQ/listener/MemberListener.java
  src/main/java/com/fourback/runus/global/rabbitMQ/publisher/MQSender.java
  src/test/HTTP/rest.http
Labels: Feat

#4 feat: 회원가입, 로그인 구현
  build.gradle
  src/main/java/com/fourback/runus/RunusApplication.java
  src/main/java/com/fourback/runus/domains/members/controller/AuthController.java
  src/main/java/com/fourback/runus/domains/members/controller/SuccessController.java
  src/main/java/com/fourback/runus/domains/members/domain/Member.java
  src/main/java/com/fourback/runus/domains/members/dto/CustomUserDetails.java
  src/main/java/com/fourback/runus/domains/members/repository/MemberRepository.java
  src/main/java/com/fourback/runus/domains/members/service/JpaUserDetailsService.java
  src/main/java/com/fourback/runus/domains/members/service/MemberService.java
  src/main/java/com/fourback/runus/global/security/config/CustomAuthenticationSuccessHandler.java
  src/main/java/com/fourback/runus/global/security/config/SecurityConfig.java
  src/main/java/com/fourback/runus/global/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/fourback/runus/global/security/filter/JwtExceptionHandlingFilter.java
  src/main/java/com/fourback/runus/global/security/provider/JwtProvider.java
  src/main/java/com/fourback/runus/global/security/util/JwtUtil.java
  src/main/resources/application.yml
  src/main/resources/static/index.html
  src/main/resources/static/login-success.html
  src/main/resources/static/register-success.html
Labels: enhancement

#7 Feat: S3 업로드 기능 구현
  .gitignore
  build.gradle
  src/main/java/com/fourback/runus/global/config/S3Config.java
  src/main/java/com/fourback/runus/global/service/S3Service.java
  src/main/resources/application.yml
Labels: enhancement

#8 Fix @Qualifier``
  .idea/modules.xml
  .idea/modules/runus.main.iml
  src/main/java/com/fourback/runus/global/rabbitMQ/exchange/TopicExchangeConfig.java
Labels: fix

#10 Feat: 로그인, 회원가입 1차 구현
  build.gradle
  src/main/java/com/fourback/runus/domains/member/controller/AuthController.java
  src/main/java/com/fourback/runus/domains/member/controller/MemberController.java
  src/main/java/com/fourback/runus/domains/member/domain/Member.java
  src/main/java/com/fourback/runus/domains/member/dto/requeset/LoginRequest.java
  src/main/java/com/fourback/runus/domains/member/repository/MemberRepository.java
  src/main/java/com/fourback/runus/domains/member/service/JpaUserDetailsService.java
  src/main/java/com/fourback/runus/domains/member/service/MemberService.java
  src/main/java/com/fourback/runus/global/amazon/config/S3Config.java
  src/main/java/com/fourback/runus/global/error/errorCode/ResponseCode.java
  src/main/java/com/fourback/runus/global/error/exception/JwtValidationException.java
  src/main/java/com/fourback/runus/global/error/handler/GlobalExceptionHandler.java
  src/main/java/com/fourback/runus/global/security/config/CorsConfig.java
  src/main/java/com/fourback/runus/global/security/config/CustomAuthenticationSuccessHandler.java
  src/main/java/com/fourback/runus/global/security/config/SecurityConfig.java
  src/main/java/com/fourback/runus/global/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/fourback/runus/global/security/filter/JwtExceptionHandlingFilter.java
  src/main/java/com/fourback/runus/global/security/provider/JwtProvider.java
  src/main/java/com/fourback/runus/global/security/util/JwtUtil.java
  src/main/resources/application.yml
  src/main/resources/static/index.html
  src/main/resources/static/login-success.html
  src/main/resources/static/register-success.html
Labels: enhancement

#15 Feature/feat kyh redis token
  .gitignore
  .idea/encodings.xml
  .idea/sqldialects.xml
  build.gradle
  src/main/java/com/fourback/runus/domains/member/controller/AuthController.java
  src/main/java/com/fourback/runus/domains/member/service/MemberService.java
  src/main/java/com/fourback/runus/global/redis/config/RedisConfig.java
  src/main/java/com/fourback/runus/global/redis/dto/GetTokenResponse.java
  src/main/java/com/fourback/runus/global/redis/service/RedisAuthHandler.java
  src/main/java/com/fourback/runus/global/redis/service/RedisUserService.java
  src/main/java/com/fourback/runus/global/security/config/RedisLogoutHandler.java
  src/main/java/com/fourback/runus/global/security/config/RedisLogoutSuccessHandler.java
  src/main/java/com/fourback/runus/global/security/config/SecurityConfig.java
  src/main/resources/application.yml
  src/test/HTTP/rest.http
Labels: Feat

#20 Feat. webSocketConnectionManageMent
  .idea/dataSources.xml
  .idea/intellij-javadocs-4.0.1.xml
  src/main/java/com/fourback/runus/domains/member/controller/AuthController.java
  src/main/java/com/fourback/runus/domains/member/service/MemberService.java
  src/main/java/com/fourback/runus/global/rabbitMQ/dto/User.java
  src/main/java/com/fourback/runus/global/rabbitMQ/dto/UserEvent.java
  src/main/java/com/fourback/runus/global/rabbitMQ/enumerate/MQExchange.java
  src/main/java/com/fourback/runus/global/rabbitMQ/publisher/MQSender.java
  src/main/java/com/fourback/runus/global/redis/config/RedisConfig.java
  src/test/HTTP/rest.http
Labels: enhancement

#21 Feat: 유저 프로필 조회 기능 구현
  .idea/jpa.xml
  .idea/misc.xml
  src/main/java/com/fourback/runus/domains/member/controller/MemberController.java
  src/main/java/com/fourback/runus/domains/member/service/MemberService.java
  src/main/java/com/fourback/runus/domains/running/dto/response/FindTodayGoalResponse.java
  src/main/java/com/fourback/runus/domains/running/dto/response/RunTotalInfosSummaryWith.java
  src/main/java/com/fourback/runus/domains/running/repository/RunTotalInfosRepository.java
  src/main/java/com/fourback/runus/global/security/config/CorsConfig.java
Labels: enhancement, fix

#22 러닝 기능 수정
  src/main/java/com/fourback/runus/domains/running/controller/RunningController.java
  src/main/java/com/fourback/runus/domains/running/domain/RunTotalInfos.java
  src/main/java/com/fourback/runus/domains/running/domain/TodayGoal.java
  src/main/java/com/fourback/runus/domains/running/dto/request/EndRunningRequest.java
  src/main/java/com/fourback/runus/domains/running/dto/response/EndRunningResponse.java
  src/main/java/com/fourback/runus/domains/running/dto/response/StartRunningResponse.java
  src/main/java/com/fourback/runus/domains/running/dto/response/TodayGoalResponse.java
  src/main/java/com/fourback/runus/domains/running/repository/TodayGoalRepository.java
  src/main/java/com/fourback/runus/domains/running/service/RunningService.java
Labels: fix
